# https://github.com/screepers/screeps-launcher
services:
  screeps-server:
    # build:
    #   context: .
    #   args:
    #     ARCH: amd64
    image: screepers/screeps-launcher
    restart: unless-stopped
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/screeps
    ports:
      - 21025:21025/tcp
    env_file:
      - .env

  screeps-mongo:
    image: mongo
    volumes:
      - screeps-mongo-data:/data/db
    restart: unless-stopped

  screeps-redis:
    image: redis
    volumes:
      - screeps-redis-data:/data
    restart: unless-stopped

volumes:
  screeps-redis-data:
  screeps-mongo-data:
  screeps-data:
